services:
  mysql:
    image: mysql:8.0
    container_name: tiendadiscos-mysql
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: tiendadiscos
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./mysql/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - tiendadiscos-net

  administracion-usuario:
    build:
      context: .
      dockerfile: AdministracionUsuario/Dockerfile
    container_name: tiendadiscos-usuario
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tiendadiscos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_PROFILES_ACTIVE: docker
      SPRING_FLYWAY_TABLE: flyway_schema_history_usuarios
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: 0
    ports:
      - "8081:8081"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiendadiscos-net

  administracion-envios:
    build:
      context: .
      dockerfile: AdministracionEnvios/Dockerfile
    container_name: tiendadiscos-envios
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tiendadiscos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_PROFILES_ACTIVE: docker
      SPRING_FLYWAY_TABLE: flyway_schema_history_envios
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: 0
    ports:
      - "8082:8082"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiendadiscos-net

  registrar-productos:
    build:
      context: .
      dockerfile: RegistrarProductos/Dockerfile
    container_name: tiendadiscos-productos
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tiendadiscos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_PROFILES_ACTIVE: docker
      SPRING_FLYWAY_TABLE: flyway_schema_history_productos
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: 0
    ports:
      - "8083:8083"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiendadiscos-net

  registrar-sede:
    build:
      context: .
      dockerfile: RegistrarSede/Dockerfile
    container_name: tiendadiscos-sede
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tiendadiscos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_PROFILES_ACTIVE: docker
      SPRING_FLYWAY_TABLE: flyway_schema_history_sede
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: 0
    ports:
      - "8084:8084"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiendadiscos-net

  registro-resenas:
    build:
      context: .
      dockerfile: RegistroResenas/Dockerfile
    container_name: tiendadiscos-resenas
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tiendadiscos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_PROFILES_ACTIVE: docker
      SPRING_FLYWAY_TABLE: flyway_schema_history_resenas
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: 0
      MS_RESENAS_URI: http://localhost:8085
    ports:
      - "8085:8085"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiendadiscos-net

  registrar-discos:
    build:
      context: .
      dockerfile: RegistrarDiscos/Dockerfile
    container_name: tiendadiscos-discos
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tiendadiscos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_PROFILES_ACTIVE: docker
      SPRING_FLYWAY_TABLE: flyway_schema_history_discos
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: 0
    ports:
      - "8086:8086"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiendadiscos-net

  administracion-descuentos:
    build:
      context: .
      dockerfile: AdministracionDescuentos/Dockerfile
    container_name: tiendadiscos-descuentos
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tiendadiscos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_PROFILES_ACTIVE: docker
      SPRING_FLYWAY_TABLE: flyway_schema_history_descuentos
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: 0
      MS_CARRITO_URI: http://localhost:8088
    ports:
      - "8087:8087"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiendadiscos-net

  carrito-compras:
    build:
      context: .
      dockerfile: CarritoCompras/Dockerfile
    container_name: tiendadiscos-carrito
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tiendadiscos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_PROFILES_ACTIVE: docker
      SPRING_FLYWAY_TABLE: flyway_schema_history_carrito
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: 0

    ports:
      - "8088:8088"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiendadiscos-net

  manejo-stock:
    build:
      context: .
      dockerfile: ManejoStock/Dockerfile
    container_name: tiendadiscos-stock
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tiendadiscos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_PROFILES_ACTIVE: docker
      SPRING_FLYWAY_TABLE: flyway_schema_history_stock
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: 0
    ports:
      - "8089:8089"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiendadiscos-net

  administracion-ventas:
    build:
      context: .
      dockerfile: AdministracionVentas/Dockerfile
    container_name: tiendadiscos-ventas
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/tiendadiscos
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: ""
      SPRING_PROFILES_ACTIVE: docker
      SPRING_FLYWAY_TABLE: flyway_schema_history_ventas
      SPRING_FLYWAY_BASELINE_ON_MIGRATE: "true"
      SPRING_FLYWAY_BASELINE_VERSION: 0
    ports:
      - "8091:8091"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiendadiscos-net

  api-gateway:
    build:
      context: ./api-gateway
      dockerfile: Dockerfile
    container_name: tiendadiscos-gateway
    environment:
      MS_USUARIO_URI: http://administracion-usuario:8081
      MS_ENVIOS_URI: http://administracion-envios:8082
      MS_PRODUCTOS_URI: http://registrar-productos:8083
      MS_SEDE_URI: http://registrar-sede:8084
      MS_RESENAS_URI: http://registro-resenas:8085
      MS_DISCOS_URI: http://registrar-discos:8086
      MS_DESCUENTOS_URI: http://administracion-descuentos:8087
      MS_CARRITO_URI: http://carrito-compras:8088
      MS_STOCK_URI: http://manejo-stock:8089
      MS_VENTAS_URI: http://administracion-ventas:8091
    ports:
      - "8080:8080"
    depends_on:
      mysql:
        condition: service_healthy
    networks:
      - tiendadiscos-net

volumes:
  mysql_data:

networks:
  tiendadiscos-net:
    driver: bridge
