-- 1. Tabla padre INFO_STOCK (hereda en PRODUCTO_STOCK vía JOINED)
CREATE TABLE INFO_STOCK (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    producto BIGINT,
    sede_id BIGINT,
    stock_actual INT NOT NULL
);

-- 2. Tabla hija PRODUCTO_STOCK (extiende INFO_STOCK con JOINED)
CREATE TABLE PRODUCTO_STOCK (
    id BIGINT PRIMARY KEY,
    tipo_producto VARCHAR(31) NOT NULL,
    id_producto BIGINT,
    FOREIGN KEY (id) REFERENCES INFO_STOCK(id) ON DELETE CASCADE
);