CREATE TABLE USUARIO_C (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    gmail VARCHAR(50) NOT NULL,
    contraseña VARCHAR(50) NOT NULL
);

CREATE TABLE PRODUCTOS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    precio INT NOT NULL
);

CREATE TABLE DISCO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    artista VARCHAR(50) NOT NULL,
    precio INT NOT NULL
);

CREATE TABLE CARRITO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    usuario_id BIGINT NOT NULL,
    descuento DOUBLE DEFAULT 0,
    FOREIGN KEY (usuario_id) REFERENCES USUARIO_C(id)
);

CREATE TABLE CARRITO_DISCOS (
    carrito_id BIGINT,
    disco_id BIGINT,
    FOREIGN KEY (carrito_id) REFERENCES CARRITO(id),
    FOREIGN KEY (disco_id) REFERENCES DISCO(id)
);

CREATE TABLE CARRITO_PRODUCTOS (
    carrito_id BIGINT,
    producto_id BIGINT,
    FOREIGN KEY (carrito_id) REFERENCES CARRITO(id),
    FOREIGN KEY (producto_id) REFERENCES PRODUCTOS(id)
);