CREATE TABLE CARRITO_DISCOS_NEW (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    carrito_id BIGINT NOT NULL,
    disco_id BIGINT NOT NULL,
    qty INT DEFAULT 1,
    FOREIGN KEY (carrito_id) REFERENCES CARRITO(id)
);

INSERT INTO CARRITO_DISCOS_NEW (carrito_id, disco_id, qty)
SELECT carrito_id, disco_id, 1 FROM CARRITO_DISCOS;

DROP TABLE CARRITO_DISCOS;

ALTER TABLE CARRITO_DISCOS_NEW RENAME TO CARRITO_DISCOS;

DROP TABLE DISCO;
