CREATE TABLE SEDES (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    direccion VARCHAR(100) NOT NULL
);

CREATE TABLE DISCOS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    artista VARCHAR(50) NOT NULL,
    precio BIGINT NOT NULL,
    sede_id BIGINT,
    FOREIGN KEY (sede_id) REFERENCES SEDES(id)
);

CREATE TABLE PRODUCTOS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    precio BIGINT NOT NULL,
    sede_id BIGINT,
    FOREIGN KEY (sede_id) REFERENCES SEDES(id)
);
