CREATE TABLE DISCOS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    artista VARCHAR(50) NOT NULL,
    precio BIGINT NOT NULL
);

CREATE TABLE PRODUCTOS (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    precio BIGINT NOT NULL
);

CREATE TABLE SEDES(
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    direccion VARCHAR(100) NOT NULL,
    FOREIGN KEY discos_id REFERENCES DISCOS(id),
    FOREIGN KEY productos_id REFERENCES PRODUCTOS(id)
);