CREATE TABLE DISCO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    artista VARCHAR(50) NOT NULL
);

CREATE TABLE USUARIO (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    nombre VARCHAR(50) NOT NULL,
    gmail VARCHAR(50) NOT NULL
);

CREATE TABLE RESENA (
    id BIGINT AUTO_INCREMENT PRIMARY KEY,
    mensaje VARCHAR(150) NOT NULL,
    user_id BIGINT NOT NULL,
    disco_id BIGINT NOT NULL,
    FOREIGN KEY (user_id) REFERENCES USUARIO(id),
    FOREIGN KEY (disco_id) REFERENCES DISCO(id)
);
