DROP TABLE IF EXISTS DESCUENTOS_PRODUCTOS;
DROP TABLE IF EXISTS DESCUENTOS_DISCO;

CREATE TABLE IF NOT EXISTS DESCUENTO_DISCOS (
    descuento_id BIGINT NOT NULL,
    disco_id BIGINT,
    FOREIGN KEY (descuento_id) REFERENCES DESCUENTO(id)
);

CREATE TABLE IF NOT EXISTS DESCUENTO_PRODUCTOS (
    descuento_id BIGINT NOT NULL,
    producto_id BIGINT,
    FOREIGN KEY (descuento_id) REFERENCES DESCUENTO(id)
);
